# Generated by Django 3.2.5 on 2023-06-16 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jury',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Judge',
        ),
    ]
