# Generated by Django 3.2.5 on 2023-06-17 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juryapp', '0002_auto_20230616_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juryapp.jury')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juryapp.panel')),
            ],
        ),
    ]
