# Generated by Django 3.2.5 on 2023-06-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juryapp', '0003_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='jury',
        ),
        migrations.RemoveField(
            model_name='message',
            name='panel',
        ),
        migrations.AddField(
            model_name='message',
            name='panel',
            field=models.ManyToManyField(to='juryapp.Panel'),
        ),
    ]
