# Generated by Django 3.2.5 on 2023-06-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juryapp', '0004_auto_20230617_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.CharField(default='Message', max_length=100),
        ),
    ]
