# Generated by Django 3.2.5 on 2023-06-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juryapp', '0007_alter_panel_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='panel',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='panel',
            name='members',
            field=models.ManyToManyField(to='juryapp.Number'),
        ),
    ]
