# Generated by Django 3.2.5 on 2023-06-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juryapp', '0008_auto_20230618_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='number',
            field=models.IntegerField(max_length=10),
        ),
    ]
