# Generated by Django 3.2.5 on 2023-06-24 17:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('juryapp', '0009_alter_number_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
