# Generated by Django 3.2.5 on 2023-06-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juryapp', '0011_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='jury',
            name='casename',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
